---

- name: Install OctoPrint via pip - latest version
  ansible.builtin.pip:
    name: octoprint
    state: present
    virtualenv: "{{ octoprint.dir }}/venv"
    virtualenv_command: virtualenv
    virtualenv_python: python3
  when: octoprint.version == 'latest'

- name: Install OctoPrint via pip - specific version
  ansible.builtin.pip:
    name: octoprint
    version: "=={{ octoprint.version }}"
    state: present
    virtualenv: "{{ octoprint.dir }}/venv"
    virtualenv_command: virtualenv
    virtualenv_python: python3
  when: octoprint.version != 'latest'

- name: Configure OctoPrint restart commands
  ansible.builtin.command: "{{ item }}"
  loop:
    - "{{ octoprint.dir }}/venv/bin/octoprint -c {{ octoprint.dir }}/config.yml config set server.commands.serverRestartCommand 'sudo systemctl restart octoprint'"
    - "{{ octoprint.dir }}/venv/bin/octoprint -c {{ octoprint.dir }}/config.yml config set server.commands.systemRestartCommand 'sudo shutdown -r now'"
    - "{{ octoprint.dir }}/venv/bin/octoprint -c {{ octoprint.dir }}/config.yml config set server.commands.systemShutdownCommand 'sudo shutdown -h now'"
  when: octoprint.state == 'present'
  changed_when: true

- name: Set directory owner and group
  ansible.builtin.file:
    path: "{{ octoprint.dir }}"
    state: directory
    recurse: true
    owner: "{{ octoprint.user }}"
    group: "{{ octoprint.group }}"
