---
# tasks file for octoprint and mjpg_streamer removal.

- name: Disable octoprint and mjpg_streamer services.
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop:
    - octoprint
    - mjpg_streamer
  register: disable_service
  ignore_errors: true

- name: Remove sudoer permissions
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: absent
    line: "{{ item }}"
    validate: /usr/sbin/visudo -cf %s
  loop:
    - "{{ webcam_user }} ALL=(ALL) NOPASSWD:/usr/bin/systemctl start mjpg_streamer"
    - "{{ webcam_user }} ALL=(ALL) NOPASSWD:/usr/bin/systemctl stop mjpg_streamer"
    - "{{ webcam_user }} ALL=(ALL) NOPASSWD:/usr/bin/systemctl restart mjpg_streamer"
    - "{{ octoprint_user }} ALL=(ALL) NOPASSWD:/usr/bin/systemctl restart octoprint"
    - "{{ octoprint_user }} ALL=(ALL) NOPASSWD:/usr/bin/systemctl start octoprint"
    - "{{ octoprint_user }} ALL=(ALL) NOPASSWD:/usr/bin/systemctl stop octoprint"
    - "{{ octoprint_user }} ALL=(ALL) NOPASSWD:/usr/bin/systemctl restart mjpg_streamer"
    - "{{ octoprint_user }} ALL=(ALL) NOPASSWD:/usr/bin/systemctl start mjpg_streamer"
    - "{{ octoprint_user }} ALL=(ALL) NOPASSWD:/usr/bin/systemctl stop mjpg_streamer"
    - "{{ octoprint_user }} ALL=(ALL) NOPASSWD:/usr/sbin/shutdown -r now"
    - "{{ octoprint_user }} ALL=(ALL) NOPASSWD:/usr/sbin/shutdown -h now"

- name: Remove files and directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/systemd/system/octoprint.service
    - /etc/systemd/system/mjpg_streamer.service
    - /etc/init.d/octoprint
    - /etc/default/octoprint
    - "{{ install_dir }}/Octoprint"
    - "{{ install_dir }}/.octoprint"
    - "{{ install_dir }}/mjpg-streamer"
    - "{{ install_dir }}/scripts"

- name: Remove dependencies.
  ansible.builtin.package:
    name:
      - build-essential
      - cmake
      - ffmpeg
      - imagemagick
      - libv4l-dev
      - libyaml-dev
      - subversion
    state: absent
  when: uninstall_dependencies

- name: Remove libjpeg
  ansible.builtin.package:
    name:
      - libjpeg62-turbo-dev
    state: absent
  when: (uninstall_dependencies and ansible_distribution != "Ubuntu") or
        (uninstall_dependencies and ansible_distribution == "Ubuntu" and ansible_distribution_major_version < "20")

- name: Remove libjpeg Ubuntu
  ansible.builtin.package:
    name:
      - libjpeg-turbo8-dev
    state: absent
  when:
    - uninstall_dependencies and ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version >= "20"
