---
# handlers file for octoprint

- name: restart_octoprint
  systemd:
    name: octoprint
    enabled: true
    state: restarted
    daemon_reload: true

- name: restart_mjpg_streamer
  systemd:
    name: mjpg_streamer
    enabled: true
    state: restarted
    daemon_reload: true
